version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  skillcode-backend:
    image: tehilathestudent/skillcode-backend:latest
    container_name: skillcode-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=skillcode_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker daemon socket for Kind
volumes:
  mongo-data:
