version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    network_mode: "host"  # Use host network
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db

  skillcode-backend:
    image: tehilathestudent/skillcode-backend:latest
    container_name: skillcode-backend
    network_mode: "host"  # Use host network
    # ports:
    #   - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - MONGO_DB=skillcode_db
      - KUBECONFIG=/root/.kube/config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker daemon socket for Kind
      - ~/.kube:/root/.kube                       # Mount kubeconfig to interact with Kind cluster
      - ./assets:/app/assets                      # Mount assets directory

volumes:
  mongo-data:
