# Use an official Go image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Set the PROJECT_ROOT environment variable
ENV PROJECT_ROOT=/app

# Copy Go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the entire project into the container
COPY . .

# Install additional dependencies for testing
RUN apt-get update && apt-get install -y netcat-openbsd

# No CMD needed here because it is overridden by docker-compose.test.yaml
