FROM python:3.10-slim


# Create a directory for the user code
WORKDIR /sandbox

# Copy the user's code into the container
COPY temp/python/main.py /sandbox/main.py

# Copy and execute the user's code
CMD ["python3", "/sandbox/main.py"]
