name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      run: |
        sudo apt-get install -y netcat
        go mod tidy
        go test ./internal/... -v

    # Step 5: Build Docker Image
    - name: Build Docker Image
      if: success()
      run: docker build -t tehilathestudent/skillcode-backend:latest .

    # Step 6: Push Docker Image to Docker Hub
    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Image
      if: success()
      run: docker push tehilathestudent/skillcode-backend:latest

    # Step 7: Run Integration Tests
    - name: Run Integration Tests
      if: success()
      run: |
        docker-compose -f docker-compose.yaml up -d mongo
        go test ./tests/integration -v
        docker-compose down

    # Step 8: Run E2E Tests
    - name: Run E2E Tests
      if: success()
      run: |
        docker-compose -f docker-compose.test.yaml up --abort-on-container-exit
