name: CI Pipeline

on:
  push:
    branches:
      - main
      - image-builder

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PROJECT_ROOT: ${{ github.workspace }}
      CLUSTER_NAME: skillcode-cluster

    steps:
      # Step: Checkout the source code repo
      - name: Checkout source code
        uses: actions/checkout@v2

      # Step: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step: Build Docker Image
      - name: Build Docker Image
        run: docker build -t tehilathestudent/skillcode-backend:${{ github.sha }} .

      # Step: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step: Push Docker Image
      - name: Push Docker Image
        run: docker push tehilathestudent/skillcode-backend:${{ github.sha }}

      # Step: Clone GitOps Repo
      - name: Clone GitOps Repo
        run: |
          git clone https://$TOKEN@github.com/TehilaTheStudent/IoC-for-argocd.git
        env:
          TOKEN: ${{ secrets.TOKEN }}

      # Step: Update Helm Values
      - name: Update Backend Image Tag in Helm Values
        run: |
          IMAGE_TAG=${{ github.sha }}
          yq e ".backend.image = \"tehilathestudent/skillcode-backend:${IMAGE_TAG}\"" -i IoC-for-argocd/skillcode-helm-chart/values.yaml

      # Step: Commit Changes to GitOps Repo
      - name: Commit Changes
        run: |
          cd IoC-for-argocd
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add skillcode-helm-chart/values.yaml
          git commit -m "Update backend image tag to ${{ github.sha }}"
          git push
